### PR TITLE
update sqlalachemy pin, add conda-forge/jupyter-book to maintainers

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Just adds the top pin to appease the `~` on sqlalchemy... and it's likely not cosmetic, there were certainly some breaking changes.

Also adds @conda-forge/jupyter-book to help maintain: I accept on our behalf.

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
Now seeing this on https://github.com/conda-forge/jupyter-book-feedstock/pull/4#issuecomment-813102565

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge/jupyter-cache once again ready for review

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

@conda-forge/jupyter-cache please consider reviewing this, still encountering issues downstream

**Comment by chrisjsewell** [comment]
Oh sorry I missed this before

**Comment by chrisjsewell** [comment]
Wanna add a pip check then?

**Comment by bollwyvl** [comment]
`pip check` was already in place, but there was no version of `sqlalchemy` in the wild greater than the `~` pin. This is just filling in some information that was previously missing.

The `1.4` line offers a lot of nice async features, and getting compatible with it would be nice, but potentially tricky.

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

@conda-forge/jupyter-cache please consider reviewing this, still encountering issues downstream

**Pull request merged**
